# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('amount', models.FloatField(verbose_name='contract amount')),
                ('untreated', models.BooleanField()),
                ('user_from', models.CharField(max_length=200)),
                ('user_to', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
